# Generated by Django 5.2.6 on 2025-10-14 19:39

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapost',
            name='file',
            field=models.FileField(upload_to=posts.models.post_media_path),
        ),
    ]
